### ISSUE TITLE
SQL query: número de casos confirmados y número de defunciones por mes a nivel nacional en 2021

### ISSUE THREAD

**Issue by jrivera15** [ProyectosMCD/Dengue#6]
Verificar si se puede hacer por mes, ya que no viene un campo de fecha de defunción.

**Comment by viowiy** [comment]
Me la quedo... deja ver como sale... jejejeje...

**Comment by viowiy** [comment]
Habían pocos fallecidos por cierto... eran apenas unos 36... Pero ahí quedó...
